### PR TITLE
Attributes

### PR DESCRIPTION
**Pull request by MatanZ**
I did not intend to add this now, but it conflicts with #91, and it will be much easier to apply this first.

The main thing this sequence of commits does is allowing attributes (bold, reverse video, etc.) to be configured, in addition to colors.

It also makes some more elements configurable, including some of #91.

Also a few small interface changes that were caught in the sequence.

### CODE REVIEW

**Comment by louipc** [comment]
Would you like to refactor this to resolve conflicts? I'll just merge it then. I thought you had push access.

**Comment by MatanZ** [comment]
This reverts the changes by Foldex in #91. It is too much work otherwise.

Some of the work in #91 is done here, and some will need to be reworked.

**Comment by louipc** [comment]
Is this ready to go?

**Comment by MatanZ** [comment]
Yes.

**Pull request merged**
