### PR TITLE
Filelist annoyances

### PR DESCRIPTION
**Pull request by MatanZ**
This fixes a few display glitches in the file list. It does not change any functionality.

### CODE REVIEW

**Comment by gangelop** [comment]
This is a nitpick but, would you mind amending the commit message of a6e5554?
https://commit.style/

**Comment by MatanZ** [comment]
Done.

**Comment by MatanZ** [comment]
I am not sure. Looking at the branch it shows OK, but here it appears as if there are 9 commits.

**Comment by gangelop** [comment]
lgtm

**Pull request merged**
